// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseNexus.Server.Data;

#nullable disable

namespace PurchaseNexus.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220113100836_NRT-Changes")]
    partial class NRTChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PurchaseNexus.Shared.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TodoListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Done = false,
                            Note = "",
                            Priority = 0,
                            State = 0,
                            Title = "Make a todo list",
                            TodoListId = 1
                        },
                        new
                        {
                            Id = 2,
                            Done = false,
                            Note = "",
                            Priority = 0,
                            State = 0,
                            Title = "Check off the first item",
                            TodoListId = 1
                        },
                        new
                        {
                            Id = 3,
                            Done = false,
                            Note = "",
                            Priority = 0,
                            State = 0,
                            Title = "Realise you've already done two things on the list!",
                            TodoListId = 1
                        },
                        new
                        {
                            Id = 4,
                            Done = false,
                            Note = "",
                            Priority = 0,
                            State = 0,
                            Title = "Reward yourself with a nice, long nap",
                            TodoListId = 1
                        });
                });

            modelBuilder.Entity("PurchaseNexus.Shared.Models.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Todo List"
                        });
                });

            modelBuilder.Entity("PurchaseNexus.Shared.Models.TodoItem", b =>
                {
                    b.HasOne("PurchaseNexus.Shared.Models.TodoList", "TodoList")
                        .WithMany("Items")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("PurchaseNexus.Shared.Models.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
